# Generated by Django 5.2.4 on 2025-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='None', max_length=70),
            preserve_default=False,
        ),
    ]
