# Generated by Django 5.2.4 on 2025-07-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
